#!/bin/bash

#########################################
#               Variables               #
#########################################

NFS_FOLDER=150.162.11.228:/usr/EDATools/


####VIRTUOSO#####
IC616_bin=/usr/edatools/cadence/IC616/bin/
IC616_bin_64=/usr/edatools/cadence/IC616/bin/64bit/
IC616_dfII=/usr/edatools/cadence/IC616/tools/dfII/bin/64bit/
IC616_tools=/usr/edatools/cadence/IC616/tools/bin/
OA_HOME=/usr/edatools/cadence/IC616/oa_v22.43.029/ 
LIB_64=/usr/lib64
VIRTUOSO_LIB1=/usr/edatools/cadence/IC616/oa_v22.43.029/lib/linux_rhel50_gcc44x_64/opt
VIRTUOSO_LIB2=/usr/edatools/cadence/IC616/tools.lnx86/lib/64bit

####INCISIVE####
VRST_HOME=/usr/edatools/cadence/INCISIV151/
SPECMAN_PATH=/usr/edatools/cadence/INCISIV151/
PATH=/usr/edatools/cadence/INCISIV151/tools.lnx86/bin:$PATH
LD_LIBRARY_PATH=:/usr/lib64:/usr/edatools/cadence/INCISIV151/tools.lnx86/systemc/lib:$LD_LIBRARY_PATH

####CTOS####


#########################################
#     Setting FOLDERS and LICENSE       #
#########################################

printf '\n'
if [[ -z $LM_LICENSE_FILE ]]; then
    export  LM_LICENSE_FILE=5280@150.162.10.199
else 
    printf '\e[1;34m%-6s\e[m\n' 'LM_LICENSE_FILE already set: to clear variable use unset <variable>'
    printf '\n'
fi

if mount | grep /usr/edatools > /dev/null; then 
    printf '\e[1;36m%-6s\e[m\n' '+==========================+'
    printf '\e[1;36m%-6s\e[m\n' '|     Already Mounted      |'
    printf '\e[1;36m%-6s\e[m\n' '+==========================+'
    printf '\n'
else 
    sudo mount -t nfs $NFS_FOLDER /usr/edatools && {
	    printf '\e[1;36m%-6s\e[m\n' '+==========================+'
	    printf '\e[1;36m%-6s\e[m\n' '|         Mounted          |'
	    printf '\e[1;36m%-6s\e[m\n' '+==========================+'
	    printf '\n'
    }	
fi

#########################################
#     Setting Env Variables INCISIVE    #
#########################################

printf '\e[1;36m%-6s\e[m\n' '+==========================+'
printf '\e[1;36m%-6s\e[m\n' '| Set. Env. Incisive 15.1  |'
printf '\e[1;36m%-6s\e[m\n' '+==========================+'
printf '\n'

export PATH
export VRST_HOME
export SPECMAN_PATH
source $VRST_HOME/env.sh -64bit
export LD_LIBRARY_PATH

#########################################
#     Setting Env Variables Virtuoso    #
#########################################


printf '\e[1;36m%-6s\e[m\n' '+==========================+'
printf '\e[1;36m%-6s\e[m\n' '| Set. Env. Virtuoso 6.16  |'
printf '\e[1;36m%-6s\e[m\n' '+==========================+'
printf '\n'

export PATH=$IC616_bin:$IC616_dfII:$IC616_bin_64:$IC616_tools:$PATH
export OA_HOME
export LD_LIBRARY_PATH=$LIB_64:$VIRTUOSO_LIB1:$VIRTUOSO_LIB2:$LD_LIBRARY_PATH

export MMSIMHOME=/usr/edatools/cadence/MMSIM131 
export PATH=$MMSIMHOME/tools.lnx86/bin:$PATH

AMSHOME=$(cds_root irun)
CDSHOME=$(cds_root virtuoso)

export AMSHOME
export CDSHOME

printf '\n' 
printf '\e[1;36m%-6s\e[m\n' 'Dont close this terminal window'
printf '\e[1;36m%-6s\e[m\n' 'Ready to rock&roll'
